name: CI / CD for token minter
on:
  push:
    branches: [ "master" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14.20.1'
          cache: 'npm'

      - name: Install dependencies
        run: npm i --force
        
      - name: Fix typescript version
        run: npm install -g typescript@4.8.2

      - name: Log local TS version
        run: node_modules/.bin/tsc -v

      - name: Build
        run: npm run build:prod

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: gh-pages
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
